### ISSUE TITLE
When a drill core section is added via the "Add drill core" button, then all present data within the drill cores is deleted.

### ISSUE THREAD

**Issue by chilimann41** [ApirsAL/GeoReVi#5]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ApirsAL** [comment]
Hey @chilimann41, thank you for your hint! Newly added drill cores were not saved automatically. I've triggered the save-action once a new drill core is added to the collection in order to save the previous ones too. 

This functionality will be available in the next version of GeoReVi. Until then, as a workaround, newly added drill cores can be saved by clicking the "Save record" button of the drilling object.
